// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqzvajzulfuatbnihhex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxenZhanp1bGZ1YXRibmloaGV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzA5NzMsImV4cCI6MjA2NjUwNjk3M30.wEVvkG0yJai5_Kf4jLtDQg7stHJBJWGtGtY2Vg09iro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);